{{- if .Values.global.admission.enabled }}
apiVersion: {{ include "webhookadmissionregistration" . }}
kind: ValidatingWebhookConfiguration
metadata:
  name: validate-namespace-deletion
webhooks:
- name: validate-namespace-deletion.gardener.cloud
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - namespaces
  failurePolicy: Fail
  namespaceSelector:
    matchLabels:
      gardener.cloud/role: project
  clientConfig:
    {{- if .Values.global.deployment.virtualGarden.enabled }}
    url: https://gardener-admission-controller.garden/webhooks/validate-namespace-deletion
    {{- else }}
    service:
      namespace: garden
      name: gardener-admission-controller
      path: /webhooks/validate-namespace-deletion
    {{- end }}
    caBundle: {{ required ".Values.global.admission.config.server.https.tls.caBundle is required" (b64enc .Values.global.admission.config.server.https.tls.caBundle) }}
- name: validate-kubeconfig-secrets.gardener.cloud
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
    - {key: gardener.cloud/role, operator: In, values: [project]}
    - {key: app, operator: NotIn, values: [gardener]}
  clientConfig:
    {{- if .Values.global.deployment.virtualGarden.enabled }}
    url: https://gardener-admission-controller.garden/webhooks/validate-kubeconfig-secrets
    {{- else }}
    service:
      namespace: garden
      name: gardener-admission-controller
      path: /webhooks/validate-kubeconfig-secrets
    {{- end }}
    caBundle: {{ required ".Values.global.admission.config.server.https.tls.caBundle is required" (b64enc .Values.global.admission.config.server.https.tls.caBundle) }}
  sideEffects: None
{{- if .Values.global.admission.config.server.resourceAdmissionConfiguration }}
- name: validate-resource-size.gardener.cloud
  rules:
    {{- range $i, $conf := .Values.global.admission.config.server.resourceAdmissionConfiguration.limits }}
  - apiGroups:
{{ toYaml $conf.apiGroups | indent 4 }}
    apiVersions:
{{ toYaml $conf.apiVersions | indent 4 }}
    operations:
    - CREATE
    - UPDATE
    resources:
{{ toYaml $conf.resources | indent 4 }}
    {{- end }}
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
      - {key: gardener.cloud/role, operator: In, values: [project]}
      - {key: app, operator: NotIn, values: [gardener]}
  clientConfig:
    {{- if .Values.global.deployment.virtualGarden.enabled }}
    url: https://gardener-admission-controller.garden/webhooks/validate-resource-size
    {{- else }}
    service:
      namespace: garden
      name: gardener-admission-controller
      path: /webhooks/validate-resource-size
    {{- end }}
    caBundle: {{ required ".Values.global.admission.config.server.https.tls.caBundle is required" (b64enc .Values.global.admission.config.server.https.tls.caBundle) }}
{{- end }}
  sideEffects: None
{{- end }}
